title: TrebledJ Pages
subtitle: 
description: >- # this means to ignore newlines until "baseurl:"
  TrebledJ's personal blog, with various posts on programming and music.

url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /posts

# Navigation
urls:
    - text: Home
      url: /
    - text: Posts
      url: /posts
    - text: Music
      url: /music
    - text: Profile
      url: /profile


# Edit Author details (For multi authors check _data/authors.yml)

author_logo: profile.png
author: Johnathan
author_bio: >-
  HKUST mathematics undergrad. Programming language fanatic. Avid bedroom composer. Likes pineapples on pizza.
  
author_email: "trebledjjj@gmail.com"
author_location:
author_website_url: trebledj.github.io
typewrite-text: I like pineapples on pizza.
hero_cover_img: sample_cover.jpg # replace this for changing homepage cover (eg. try cover.jpeg). Image should be in /assets/img

# Experiences
author_work_experiences:
            # - company_name: Google
            #   company_logo: google.png
            #   company_url: https://google.com
            #   designation: 
            #   description: 
            #   visibility: true

# Education
author_education_details:
              # - college_logo: mit.png
              #   college_name: MIT
              #   college_url: https://mit.org
              #   college_degree: 
              #   description: 
              #   visibility: true

# Projects
author_project_details:
              # - project_thumbnail: gamershub.png
              #   project_title: Gamers Hub
              #   project_description: A Platform built for Gamers and Game Devs
              #   project_url: https://gamershub.in
              #   visibility: true

author_skills:
  - 
    skill: C++
    strength: 9.9
    desc: Language features (templates, classes, C++11 lambdas, parameter packs, template metaprogramming, type traits, constexpr and its variants, C++20 Big4), patterns, idioms, nuances, debugging.
    tag: cpp
    subskills:
      -
        skill: CMake
        strength: 7
      -
        skill: Qt
        strength: 7.5
        desc: Development cycle, library modules, MVC concept, nuances.
        tag: qt
  -
    skill: Python
    strength: 9.8
    desc: Language features (classes, f-strings, decorators, args/kwargs, pattern matching), patterns, standard libraries (math, regex, collections, itertools, functools).
    tag: python
    subskills:
      - 
        skill: numpy
        strength: 6
      -
        skill: matplotlib
        strength: 6.5
      -
        skill: pwntools
        strength: 7.5
      -
        skill: z3
        strength: 7.9
      -
        skill: angr
        strength: 7.4
  -
    skill: C
    strength: 9.4
    desc: Language nuances, common vulnerabilities, patterns, idioms, macros.
    tag: c
  - 
    skill: Haskell
    strength: 8.8
    active: Learning memoisation, lens.
    desc: Language constructs (control flow, typeclasses and instances, modules), functional programming, standard library (list, unordered containers, IO, Control.Monad), parser combinators, monads (IO, ST), language extensions (implicit params), build systems (cabal, stack), testing (hspec), benchmarking (criterion).
    tag: haskell
  -
    skill: Rust
    strength: 5.1
    active: Learning standard library, concurrency.
    desc: Language features (borrowing, iterators, pattern matching, structs and ADTs, traits), build system (cargo).
    tag: rust
  - 
    skill: Scala
    strength: 7.5
    active: Using at work.
    desc: Scala 2, Scala 3, language features (ADTs, type bounds, implicit params), standard library (containers, filesystem), build system (maven, sbt).
    tag: scala
    subskills:
      - 
        skill: Spark
        strength: 6.8
        active: Using at work.
        desc: Jobs, SQL, dataframes.
  - 
    skill: HTML/CSS
    strength: 7.9
    active: trebledj.github.io
    desc: Tags, attributes, flex, scss.
    subskills:
      - 
        skill: Bootstrap
        strength: 7.1
        active: trebledj.github.io
  -
    skill: QML
    strength: 7.5
    desc: Development cycle, library modules, language features (transitions, behaviours, attached properties).
    tag: qml
  - 
    skill: Javascript
    strength: 6.4
    active: trebledj.github.io
    desc: Basics, ES6 (classes syntax sugar, lambdas, rest parameters), DOM, JQuery.
  -
    skill: Shell
    strength: 8
    desc: Shell scripting, unix commands (mv, ls, cp, scp, sudo), control flow, bash.
  - 
    skill: SQL
    strength: 8.2
    active: Using at work.
    desc: CRUD operations, CTEs, Spark SQL, prepared statements, SQL injection.
  -
    skill: OOP
    strength: 9.3
    desc: Classes, inheritance, interfaces, ABCs, polymorphism, encapsulation, virtual functions, design patterns.
  -
    skill: FP
    strength: 9.1
    desc: Recursion, higher order functions (map, filter, fold), ADTs (sum types), functors, applicatives, monads.
  -
    skill: Algo and DS
    strength: 7.8
    desc: Search/sorting algorithms, graph algorithms, algo design.
  -
    skill: Embedded
    strength: 7.2
    desc: Microcontrollers, core concepts (PWM, ADC), communication protocols (UART, CAN), FreeRTOS, STM32.
    tag: embedded
  -
    skill: Binary Pwn
    strength: 7.5
    desc: Buffer overflow, ROP, ret2text, ret2libc.
    tag: pwn
  -
    skill: Reverse
    strength: 8.4
    desc: x86 assembly, objdump, decompilers (ghidra), symbolic execution (z3, angr).
    tag: reverse
  -
    skill: Mathematics
    strength: 0.4
    active: \"Mathematics is everywhere.\"
    desc: The more I learn, the less I know.
    tag: mathematics



# social links
github_username: TrebledJ

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: ...
hyvor_talk_website_id:

# wakatime username (coding activity)
wakatime_username: 

# mailchimp embedded form url (newsletter):
mailchimp_form_url: 

# contact form - (choose formspress or getform)
getform_endpoint: 
formspree_email: 

# releases - widget can be (sidebar, modal or embed)
olvy_organization: 
olvy_widget_type: 

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show (can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# pagination of posts
paginate: 8
per_page: 10
paginate_path: "/posts/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

soundcloud_color: 2631c8

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

collections_dir: collections
collections:
  posts:
    output: true
    permalink: /posts/:title/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "trebledj"
      thumbnail: "/assets/img/thumbnail.png"
      include_thumbnail: false
  -
    scope:
      path: "tags"
    values:
      layout: "tag_page"
  # -
  #   scope:
  #     path: ""
  #     type: authors
  #   values:
  #     layout: author
  #     permalink: /posts/authors/:slug
  -
    scope:
      path: 'assets/**'
    values:
      sitemap: false

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-admin

# Jekyll Admin Config
jekyll_admin:
  # hidden_links:
  #   - posts
  #   - pages
  #   - staticfiles
  #   - datafiles
  #   - configuration
  homepage: "posts"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

### Switching Deployment Strategy (in DEPLOY_STRATEGY) file change the key accordingly:
# none - For no default
# gh-pages - For Github Pages
# firebase - For Firebase Hosting

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - assets/bower_components/isotope-layout/README.md
  - assets/bower_components/icono/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-svg-core/README.md
  - assets/bower_components/ghosthunter/README.md
  - assets/bower_components/nanobar/README.md
  - assets/bower_components/lightgallery/demo/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-brands-svg-icons/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-solid-svg-icons/README.md
  - assets/bower_components/jquery-mousewheel/README.md
  - assets/bower_components/get-size/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome/README.md
  - assets/bower_components/jquery-mousewheel/ChangeLog/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-regular/README.md
  - assets/bower_components/desandro-matches-selector/README.md
  - assets/bower_components/ev-emitter/README.md
  - assets/bower_components/font-awesome/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-solid/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-webfonts/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-brands/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-common-types/README.md
  - assets/bower_components/ghosthunter/example/Index.html
  - assets/bower_components/lightgallery/test/lightgallery.html
  - assets/bower_components/masonry-layout/README.md
  - assets/bower_components/imagesloaded/README.md


destination: ./build
