name: Check Broken Links

on:
  # repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "00 02 * * 6"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: site

      - name: Check Links
        id: lychee
        uses: lycheeverse/lychee-action@v1.8.0
        with:
          args: --verbose --no-progress --include-verbatim .site
          fail: true
