name: Check Broken Links

on:
  # repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "00 12 * * 5" # HKT 8PM Friday

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: site

      - name: Restore Lychee Cache
        uses: actions/cache@v3
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-

      # TODO: --include-fragments (v0.16?)
      - name: Check Links
        id: lychee
        uses: lycheeverse/lychee-action@v1
        with:
          args: --base https://trebledj.github.io --no-progress --accept '200,201,202,203,204,403,429' --include-verbatim --exclude-path _site/404.html --cache --max-cache-age 3d _site

      - name: Create Issue From File
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
