# Workflow for building and deploying an Eleventy site to a local site branch (for further workflow automation)
name: Deploy

on:
  # Runs on pushes targeting the default branch
  push:
    branches: master
    paths:
      - '.github/workflows/src.deploy.yml'
      - '*.json'
      - '_data/**'
      - '_includes/**'
      - 'assets/**'
      - 'content/**'
      - 'eleventy/**'
      - 'pages/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Environment variables
env:
  DEPLOY_TO_GHPAGES: false       # Set `true` to deploy to GitHub Pages.

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all commit history.

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Restore 11ty Cache
        uses: actions/cache@v4
        with:
          path: .cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-eleventy-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: ${{ runner.os }}-eleventy-${{ hashFiles('**/package-lock.json') }}-

      - name: Restore npm Cache
        id: cache-npm
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        if: steps.cache-npm.outputs.cache-hit != 'true'
        run: npm ci

      - name: Build
        run: |
          echo "## Build Output" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          npm run prod >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

      - name: Commit & Push Site Build
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Build site from GitHub Actions
          branch: site
          create_branch: true

          file_pattern: '_site/**'

          commit_options: '--no-verify --signoff'
          add_options: '-f'
          push_options: '--force'

          skip_checkout: true
          skip_dirty_check: true
          skip_fetch: true

      - name: Upload Artifact
        if: env.DEPLOY_TO_GHPAGES
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site/

  deploy-ghpages:
    environment:
      name: github-pages
      # url: ${{ steps.deployment.outputs.page_url }}
      # url: trebledj.github.io
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        if: env.DEPLOY_TO_GHPAGES
        uses: actions/deploy-pages@v4